services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka3
    hostname: kafka3
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@192.168.182.58:9093,2@192.168.182.59:9093,3@192.168.182.60:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_LISTENERS: CONTROLLER://:9093,SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://192.168.182.60:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
    volumes:
      - ./kraft-data:/tmp/kraft-data
      - ./kraft-logs:/tmp/kraft-logs
      - ./config:/etc/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    command: [ "/opt/kafka/bin/kafka-server-start.sh", "/etc/kafka/kafka.properties" ]

