services:
  kowl:
    image: docker.redpanda.com/redpandadata/console:v2.8.2
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: "192.168.182.58:9092,192.168.182.59:9092,192.168.182.60:9092"
      KAFKA_SASL_ENABLED: "true"
      KAFKA_SASL_MECHANISM: "PLAIN"
      KAFKA_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
      KAFKA_SASL_USERNAME: "user1"
      KAFKA_SASL_PASSWORD: "xxx"